name: Firebase Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - run: printf $bibconfig >> api/config.ini
      - name: Deploy API
        uses: google-github-actions/deploy-cloud-functions@v0.4.0
        with:
            name: bibvis-api
            region: europe-west2
            runtime: python37
            source_dir: ./api
            credentials: ${{ secrets.GCLOUD }}
      - run: npm ci
      - run: npm run build
      - name: Deploy Web
        uses: w9jds/firebase-action@v1.5.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./web
